cc_binary(
	name = "main",
	srcs = ["main.cpp"],
	deps = [
		"@com_github_marpaia_alpaca_trade_api_cpp//alpaca:alpaca",
	],
)

cc_library(
	name = "client",
	srcs = ["client.cpp"],
	hdrs = ["client.h"],
)
